name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true
      - uses: lumaxis/shellcheck-problem-matchers@v1
        with:
          format: gcc
      - name: ShellCheck
        run: find . -type f -path './cookbooks/*/bin/*' -exec shellcheck --format gcc {} +
      - run: echo '::remove-matcher owner=shellcheck-gcc::'
      - run: sudo env PATH="$PATH" bundle exec itamae local recipe.rb --node-yaml node.example.yaml
